Users/akanksha/pythonrepochanges
ni/nisemi-python pull request #13
Opened 2023-04-17 11:40 UTC by Akanksha-NI

### What does this Pull Request accomplish?

To change SDC `version` to `23.3` and name to nisdc.

### Why should this Pull Request be merged?

To change SDC `version` to `23.3` and name to nisdc.

2023-04-17 15:03 UTC, jazbell3 approved these changes

2023-04-17 15:04 UTC, jazbell3 commented
@Akanksha-NI, I have approved the pull request. Let me know if you need any other input from my side

2023-04-19 04:42 UTC, Tharun-Sundar requested changes

2023-04-19 04:42 UTC, Tharun-Sundar commented on README.md
Why are the utility APIs removed here?

2023-04-21 11:46 UTC, Tharun-Sundar approved these changes

2023-04-21 13:08 UTC, closed without merging